Sprint9/us299/mike
AaronStahley/SER401-BLSI pull request #62
Opened 2019-03-23 07:38 UTC by michaelkasper

2019-03-23 18:32 UTC, AaronStahley requested changes
Refer to issue #63

2019-03-23 22:52 UTC, michaelkasper commented
Found the bug causing the issue. had the good state id mapping to the bad and the bad to good. Small typo, fixed now and everything seems good

2019-03-23 23:03 UTC, AaronStahley approved these changes

2019-03-23 23:05 UTC, AaronStahley requested changes
Not sure why this is happening. issue #64, #65

2019-03-26 02:00 UTC, AaronStahley approved these changes

2019-03-26 02:02 UTC, merged